apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: node4k8s-hpa
  labels:
    app: node4k8s
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: node4k8s
  minReplicas: 3
  maxReplicas: 15
  metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: 70
    - type: Resource
      resource:
        name: memory
        targetAverageUtilization: 75
